# Configuracion para produccion en Render

spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8hqspddt1ts73ejt63g-a.ohio-postgres.render.com:5432/gestor_camiones}?sslmode=require&stringtype=unspecified
spring.datasource.username=${DB_USERNAME:transportemp}
spring.datasource.password=${DB_PASSWORD:TMLv3UBMz8HY34HY7Yh5yOm596yuXqUz}

app.backup.base-dir=backups
app.backup.external-dir=/app/backups_externos
app.backup.drive-dir=/app/backups_drive
app.backup.pg-dump-path=pg_dump
app.backup.pg-restore-path=pg_restore
app.backup.encryption-key=${BACKUP_ENCRYPTION_KEY:GestorCamionesBackupKey-Prod-ChangeMe}
app.backup.retention-days=30
app.backup.drive.enabled=${BACKUP_DRIVE_ENABLED:false}
app.backup.drive.credentials-file=${BACKUP_DRIVE_CREDENTIALS_FILE:/app/credentials/google-drive.json}
app.backup.drive.folder-id=${BACKUP_DRIVE_FOLDER_ID:1DxBnp0hgfefIQKj3RBzMzXAfmFY57oZj}
